# Generated by Django 3.1.4 on 2020-12-01 10:21

import uuid

import django.contrib.postgres.operations
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        django.contrib.postgres.operations.TrigramExtension(),

        migrations.CreateModel(
            name='PhoneNumbering',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='идентификатор')),
                ('code', models.SmallIntegerField(db_index=True, verbose_name='код')),
                ('start', models.IntegerField(verbose_name='начало нумерации')),
                ('end', models.IntegerField(verbose_name='окончание нумерации')),
                ('count', models.IntegerField(verbose_name='количество')),
                ('operator_name', models.CharField(max_length=500, verbose_name='наименование оператора')),
                ('region_name', models.CharField(max_length=250, verbose_name='наименование региона')),
            ],
            options={
                'verbose_name': 'справочник нумерации телефонных номеров',
                'verbose_name_plural': 'справочники нумерации телефонных номеров',
                'db_table': 'phonenumbering',
            },
        ),
    ]
